highlighter: rouge
baseurl: /esc19
menu_header: ESC19
exercises_repo: https://github.com/infn-esc/esc19/blob/master
menu:
  -
    name: basic
    label: BASICS
    items:
    - name: environment
      label: Environment
    - name: compiling
      label: Compiling
    - name: formatting
      label: Formatting
  - name: architecture
    label: ARCHITECTURE
    items:
    - name: discoverHW
      label: Discover Hardware Architecture
    - name: perf
      label: Profiling using "perf"
  - name: memory
    label: MEMORY
    items:
    - name: memoryMonitoring
      label: Memory Monitoring Tools
    - name: MemoryAbuse
      label: Memory Abuses
    - name: DataLocality
      label: Data Locality
  - name: cpp
    label: C++
    items:
    - name: algorithms
      label: Algorithms
    - name: issues
      label: Memory issues
    - name: pointers
      label: Managing resources
    - name: move
      label: Move
    - name: containers
      label: Containers

  -
    name: floatingpoint
    label: FLOATING POINT
    items:
    - name: fpbasic
      label: Basic
    - name: quadsolver
      label: Second Order Equation
  -
    name: vectorization
    label: VECTORIZATION
    items:
    - name: pi
      label: Vectorize computation of pi
    - name: binning
      label: Vectorize the filling of an histogram
  - name: parallelism
    label: PARALLELISM
    items:
    - name: parcpp
      label: Parallel C++
    - name: cuda
      label: CUDA
    - name: mpi
      label: MPI

defaults:
  -
    scope:
      path: "basic/"
      type: "posts"
    values:
      category: "basic"
      layout: "main"
